name: Send Emails
on: 
  push: 
    paths: 
      - '**/*'  # match all files 
jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3
    - name: Run script
      run: python .github/send_emails.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-2
        CHANGED_FILES: ${{ github.event.push.files[*] }}

